" vundle
set rtp+=~/.vim/bundle/Vundle.vim

" let g:jedi#auto_initialization = 0

call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'ervandew/supertab'
Plugin 'tpope/vim-fugitive'
" zen coding
Plugin 'vim-scripts/Emmet.vim'
Plugin 'scrooloose/syntastic'
Plugin 'jmcantrell/vim-virtualenv'
"Plugin 'vim-scripts/pep8'
Plugin 'jpythonfold.vim'

Plugin 'asins/vimcdoc'

"Syntax
"Plugin 'pangloss/vim-javascript'
"Plugin 'jelera/vim-javascript-syntax'
"Plugin 'digitaltoad/vim-jade'

" Colorschemes
Plugin 'altercation/vim-colors-solarized'

" Completion
"Plugin 'ahayman/vim-nodejs-complete'

Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'
"node general - gf
"Plugin 'moll/vim-node'

"clickable
"Plugin 'Rykka/clickable.vim'
"Plugin 'Rykka/clickable-things'
"Plugin 'Rykka/os.vim'
"
"Plugin 'Rykka/riv.vim'

"node snippets; dump this to vim-snippets
" Plugin 'jamescarr/snipmate-nodejs'

"dash
"Plugin 'rizzatti/funcoo.vim'
"Plugin 'rizzatti/dash.vim'

Plugin 'tpope/vim-surround'
Plugin 'jiangmiao/auto-pairs'

"octopress and markdown
Plugin 'tangledhelix/vim-octopress'
call vundle#end()
filetype plugin indent on

autocmd BufNewFile,BufRead *.markdown,*.textile,*.md set filetype=octopress

syntax on

if version >= 603
    set helplang=cn
endif

if has('gui_running')
  "set background=light
  set background=dark
  colorscheme solarized
else
  colorscheme morning
  "set background=dark
endif

if has("unix")
  map ,e :e <C-R>=expand("%:p:h") . "/" <CR>
  map ,sp :sp <C-R>=expand("%:p:h") . "/" <CR>
  map ,sa :sav <C-R>=expand("%:p:h") . "/" <CR>
  map ,w :w <C-R>=expand("%:p:h") . "/" <CR>
else
  map ,e :e <C-R>=expand("%:p:h") . "\\" <CR>
  map ,sp :sp <C-R>=expand("%:p:h") . "\\" <CR>
  map ,sa :sav <C-R>=expand("%:p:h") . "\\" <CR>
  map ,w :w <C-R>=expand("%:p:h") . "\\" <CR>
endif

set autoread
set autoindent
set wildmenu
set cmdheight=2
set wmh=0
set linebreak
set expandtab
set textwidth=79
set softtabstop=4
set shiftwidth=4
set formatoptions+=mM
"set ffs=unix,dos,mac

" CTRL-A, CTRL-X
set nrformats=hex

set hlsearch
" nmap <F2> :set invhlsearch<CR>
map <F6> :shell<CR>
nmap <F5> :e ++enc=cp936<CR>
map <Leader>cd :cd %:p:h<CR>
map ;; :%s:::g<Left><Left><Left>
cmap ;\ \(\)<Left><Left>
map <C-K> <C-W>k<C-W>_
map <C-J> <C-W>j<C-W>_

ia xdate <c-r>=strftime("%Y-%m-%d %H:%M:%S")<cr>
ia xname Xu Hao

function! CurDir()
  let curdir = substitute(getcwd(), '/Users/haoxu/', "~/", "g")
  return curdir
endfunction

set statusline=%<%f%h%m%r\ [%{CurDir()}]\ [%{fugitive#statusline()}]%=\ 0x%B\ %b\ %Y\ %{&ff}\ %{&enc}\ %{&fenc}\ %l\/\%L,%c%V\ %P
set laststatus=2 "always show statusline

"au FileType html,css setl shiftwidth=2
"au FileType html,css setl tabstop=2
au FileType python setl shiftwidth=4
au FileType python setl tabstop=4
au FileType vim,javascript setl shiftwidth=2
au FileType vim,javascript setl tabstop=2
au FileType javascript call JavaScriptFold()
